export type RegisteredFarmer2026Record = {
  name: string;
  station: string;
  bankAccountNumber: string | null;
  ifscCode: string | null;
  panNumber: string | null;
  aadharNumber: string | null;
  village: string | null;
  postOffice: string | null;
  policeStation: string | null;
  district: string | null;
  state: string | null;
  pincode: string | null;
};

export const REGISTERED_FARMERS_2026: RegisteredFarmer2026Record[] = [
  {
    name: "Angrez Singh S/O Kirpal Singh",
    station: "Baheri",
    bankAccountNumber: "912010025736394",
    ifscCode: "UTIB0001569",
    panNumber: "ASYPS6023K",
    aadharNumber: "466906558296",
    village: "Pateri Farm",
    postOffice: "Pachpera",
    policeStation: "Baheri Police Station",
    district: "Bareilly",
    state: "Uttar Pradesh",
    pincode: "243201",
  },
  {
    name: "Udayvir Singh +1 (30+10 beegha)",
    station: "Baheri",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Navdeep Singh Gill S/o",
    station: "Baheri",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Tarsem Singh S/o",
    station: "Baheri",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Anshuman Singh S/O Ravi Kumar Singh",
    station: "Kashipur",
    bankAccountNumber: "0242104000115544",
    ifscCode: "IBKL0000242",
    panNumber: "FYCPS4808B",
    aadharNumber: "328184997525",
    village: "Kunda",
    postOffice: "Kunda",
    policeStation: "Kashipur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "244713",
  },
  {
    name: "Dilbag Singh SherGill S/O Pargat Singh",
    station: "Kashipur",
    bankAccountNumber: "0242104000065919",
    ifscCode: "IBKL0000242",
    panNumber: "BGJPS6631R",
    aadharNumber: "747448368712",
    village: "Lalpur",
    postOffice: "Kunda",
    policeStation: "Kashipur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "244713",
  },
  {
    name: "Gulraj Singh S/O Jagir Singh (Kasipur/Ajitpur)",
    station: "Kashipur",
    bankAccountNumber: "11207368843",
    ifscCode: "SBIN0007213",
    panNumber: "BGGPS6955K",
    aadharNumber: "293801690908",
    village: "Dabhaura Mustakam",
    postOffice: "Maldhanchaur",
    policeStation: "Kashipur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "244713",
  },
  {
    name: "Gurinder Singh S/O Harpal Singh",
    station: "Kashipur",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: "CCUPB8450K",
    aadharNumber: "439628511334",
    village: "Missarwala",
    postOffice: "Kunda",
    policeStation: "Kashipur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "244713",
  },
  {
    name: "Gurvinder Singh S/O Manjeet Singh",
    station: "Kashipur",
    bankAccountNumber: "0262000101286844",
    ifscCode: "PUNB0026200",
    panNumber: "CZYPS2227J",
    aadharNumber: "394121480570",
    village: "Shivrajpur",
    postOffice: "Shivrajpur",
    policeStation: "Kashipur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "244713",
  },
  {
    name: "Iqbal Singh Sahota S/O Ratan Singh Sahota",
    station: "Kashipur",
    bankAccountNumber: "160101501831",
    ifscCode: "ICIC0001601",
    panNumber: "APXPS1068J",
    aadharNumber: "761917523589",
    village: "Jaitpur Ghosi",
    postOffice: "Pratappur",
    policeStation: "Kashipur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "244713",
  },
  {
    name: "Jora Singh S/O Surjan Singh",
    station: "Kashipur",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Navneet Kumar S/O Balveer Singh",
    station: "Kashipur",
    bankAccountNumber: "NO PAYMENT DONE",
    ifscCode: "NO PAYMENT DONE",
    panNumber: "CQMPK0918H",
    aadharNumber: "678952647698",
    village: "Angadpur",
    postOffice: "Dharampur",
    policeStation: "Jaspur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "244712",
  },
  {
    name: "Paramjeet Singh S/O Sadhu Singh Bains & Simranjeet",
    station: "Kashipur",
    bankAccountNumber: "NO PAYMENT DONE",
    ifscCode: "NO PAYMENT DONE",
    panNumber: "AWYPS8895F",
    aadharNumber: "865580338425",
    village: "Baintwala",
    postOffice: "Kunda",
    policeStation: "Kashipur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "244713",
  },
  {
    name: "Samar Pal Singh Grewal S/O Inderjeet Singh Grewal",
    station: "Kashipur",
    bankAccountNumber: "0242104000117067",
    ifscCode: "IBKL0000242",
    panNumber: "ADWPS6301H",
    aadharNumber: "672877546129",
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Sanjot Kaur W/O Bhupinder Singh (Kalagarh/Kashipur)",
    station: "Kashipur",
    bankAccountNumber: "0515000105731606",
    ifscCode: "PUNB0051500",
    panNumber: null,
    aadharNumber: null,
    village: "Kaunkhera",
    postOffice: null,
    policeStation: null,
    district: "Bijnor",
    state: "Uttarakhand",
    pincode: null,
  },
  {
    name: "Satvinder Singh S/O Harbhajan Singh",
    station: "Kashipur",
    bankAccountNumber: "917010051639709",
    ifscCode: "UTIB0000406",
    panNumber: "ERFPS0783C",
    aadharNumber: "301088587252",
    village: "Dheemarkhera",
    postOffice: "Mahuwakhera",
    policeStation: "Kichha Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "244713",
  },
  {
    name: "Tejender Singh S/O Chain Singh",
    station: "Kashipur",
    bankAccountNumber: "50200112225351",
    ifscCode: "HDFC0007434",
    panNumber: "CQFPS6051L",
    aadharNumber: "376551030301",
    village: "Kashipur",
    postOffice: "Shivrajpur",
    policeStation: "Kashipur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "244713",
  },
  {
    name: "Ajit Singh Punia S/O Harkewal Singh",
    station: "Bazpur",
    bankAccountNumber: "4430008800006517",
    ifscCode: "PUNB0070010",
    panNumber: "BVXPS8588N",
    aadharNumber: "411429932657",
    village: "Rajpur No 1",
    postOffice: "Jogipura",
    policeStation: "Bazpur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "262401",
  },
  {
    name: "Karnaveer Singh S/o Omprakash Singh",
    station: "Bazpur",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Bhupinder Singh (Banna Kheda)",
    station: "Bazpur",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Amarjit Singh S/O Harpal Singh +1",
    station: "Bazpur",
    bankAccountNumber: "50100434883490",
    ifscCode: "HDFC0004720",
    panNumber: "EKEPS6225R",
    aadharNumber: "430295849608",
    village: "Sector-44 B",
    postOffice: "Sector 44 (Chandigarh)",
    policeStation: null,
    district: "Chandigarh",
    state: "Chandigarh",
    pincode: "160047",
  },
  {
    name: "Choudhary Rampal (Persad Khera)",
    station: "Bazpur",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Digvijay Singh",
    station: "Bazpur",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Dilmohan Singh S/O Bakshish Singh",
    station: "Bazpur",
    bankAccountNumber: "911010017403618",
    ifscCode: "UTIB0000053",
    panNumber: "AMAPS1682E",
    aadharNumber: "762776335607",
    village: "4004 Haritage Appartment 5 Park Road",
    postOffice: "Secretariat (Lucknow)",
    policeStation: null,
    district: "Lucknow",
    state: "Uttar Pradesh",
    pincode: "226001",
  },
  {
    name: "Gurpal Singh S/O Satnam Singh & Satnam Singh S/O Jagir Singh",
    station: "Bazpur",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: "FNJPS8439G",
    aadharNumber: "367816951209",
    village: null,
    postOffice: "Bannakhera",
    policeStation: "Kashipur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "262401",
  },
  {
    name: "Jagjeet Singh S/O Satnam Singh",
    station: "Bazpur",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Harcharan Singh Sandhu & Surender Singh",
    station: "Bazpur",
    bankAccountNumber: "50100242978828",
    ifscCode: "HDFC0004720",
    panNumber: "CHTPS0424G",
    aadharNumber: "889991887141",
    village: "Banna Khera",
    postOffice: "Bazpur",
    policeStation: "Bazpur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "262401",
  },
  {
    name: "Hardeep Singh S/O Nouniha Singh",
    station: "Bazpur",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Harinder Singh Hooda S/O Inder Singh",
    station: "Bazpur",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Jasjeet Singh S/O Surjeet Singh",
    station: "Bazpur",
    bankAccountNumber: "NO PAYMENT DONE",
    ifscCode: "NO PAYMENT DONE",
    panNumber: "HXZPS7041J",
    aadharNumber: "955105653984",
    village: "Nayagaon",
    postOffice: "Nanka Rani",
    policeStation: "Swaar Police Station",
    district: "Rampur",
    state: "Uttar Pradesh",
    pincode: "244924",
  },
  {
    name: "Jobandeep Singh S/O Narender Singh & Narender S/O Jagir Singh",
    station: "Bazpur",
    bankAccountNumber: "1362002000005654",
    ifscCode: "NTBL0BAZ136",
    panNumber: null,
    aadharNumber: "708319465887",
    village: "Keshowala",
    postOffice: "Bazpur",
    policeStation: "Bazpur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "262401",
  },
  {
    name: "Manmohan Singh Sandhu S/O Kuldeep Singh",
    station: "Bazpur",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: "ECYPS1978H",
    aadharNumber: "917378561189",
    village: "Dharampur Uttri",
    postOffice: "Manpur",
    policeStation: "Swaar Police Station",
    district: "Rampur",
    state: "Uttar Pradesh",
    pincode: "244924",
  },
  {
    name: "Mohinder Singh S/O Prem Singh",
    station: "Bazpur",
    bankAccountNumber: "06560100003962",
    ifscCode: "BARB0SULNAI",
    panNumber: "AXXPS9823M",
    aadharNumber: "626499024995",
    village: "Sarkara",
    postOffice: "Karanpur",
    policeStation: "Kashipur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "244713",
  },
  {
    name: "Prabjot Singh S/O Jasveer Singh",
    station: "Bazpur",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Ranjeet Singh Brah S/O Chanan Singh",
    station: "Bazpur",
    bankAccountNumber: "NO PAYMENT DONE",
    ifscCode: "NO PAYMENT DONE",
    panNumber: "EGIPS5354D",
    aadharNumber: "422369692288",
    village: "Beria",
    postOffice: "Bazpur",
    policeStation: "Bazpur Police Station",
    district: "Udham Singh Nagar",
    state: "Uttarakhand",
    pincode: "262401",
  },
  {
    name: "Ranjit Singh Gill S/O Gyan Singh Gill",
    station: "Bazpur",
    bankAccountNumber: "50100170857719",
    ifscCode: "HDFC0004720",
    panNumber: "AQYPG5630J",
    aadharNumber: "572616417714",
    village: "Fauji Colony",
    postOffice: null,
    policeStation: null,
    district: "Udham Singh Nagar",
    state: null,
    pincode: null,
  },
  {
    name: "Sartaj Singh Sidhu S/O Hardev Singh Sidhu",
    station: "Bazpur",
    bankAccountNumber: "07002191005980",
    ifscCode: "PUNB0070010",
    panNumber: "HNFPS2943B",
    aadharNumber: "741779948278",
    village: "Arsal Parsal",
    postOffice: "Suar",
    policeStation: "Swaar Police Station",
    district: "Rampur",
    state: "Uttar Pradesh",
    pincode: "244924",
  },
  {
    name: "Habibjaan",
    station: "Bazpur",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Shalini Gupta W/O Vishal Goyal",
    station: "Bazpur",
    bankAccountNumber: "922010042158875",
    ifscCode: "UTIB0000517",
    panNumber: "GCFPS3849E",
    aadharNumber: "472706817173",
    village: "Nandapur",
    postOffice: null,
    policeStation: null,
    district: "Udham Singh Nagar",
    state: null,
    pincode: null,
  },
  {
    name: "Vineeta Singh W/O Prabhakar Vardhan Singh",
    station: "Bazpur",
    bankAccountNumber: "NO PAYMENT DONE",
    ifscCode: "NO PAYMENT DONE",
    panNumber: "ASYPS5989C",
    aadharNumber: "944248322211",
    village: "B-149",
    postOffice: "Mahanagar",
    policeStation: null,
    district: "Lucknow",
    state: "Uttar Pradesh",
    pincode: "226006",
  },
  {
    name: "Ravi Singh",
    station: "Pantnagar",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Sunil Dogra",
    station: "Pantnagar",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
  {
    name: "Tejinder Singh Sandhu S/O Charan Singh Sandhu",
    station: "Haridwar",
    bankAccountNumber: "1064000101207303",
    ifscCode: "PUNB0106400",
    panNumber: "CGIPS4651K",
    aadharNumber: "413877686149",
    village: "Samaspur Katebar Laldang Haridwar",
    postOffice: "Haridwar",
    policeStation: "Shyampur Police Station",
    district: "Haridwar",
    state: "Uttarakhand",
    pincode: "249401",
  },
  {
    name: "Amandeep Singh S/O Jaspal Singh",
    station: "Banda",
    bankAccountNumber: "50100154605215",
    ifscCode: "HDFC0004846",
    panNumber: "FOKPS5842K",
    aadharNumber: "576177829835",
    village: "Banda",
    postOffice: "Banda (Shahjahanpur)",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242042",
  },
  {
    name: "Balveer Kaur W/O Manpreet Singh",
    station: "Banda",
    bankAccountNumber: "34645569437",
    ifscCode: "SBIN0001113",
    panNumber: "GKHPK2970L",
    aadharNumber: "391330120640",
    village: "Jamunia",
    postOffice: "Dudwa",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242042",
  },
  {
    name: "Deepak Kumar S/O Tirath Ram Sharma",
    station: "Banda",
    bankAccountNumber: "000613000001487",
    ifscCode: "UPCB00SJDCB",
    panNumber: "FBYPK7537N",
    aadharNumber: "452991707301",
    village: "Dadiuri",
    postOffice: "Mohiuddinpur",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242042",
  },
  {
    name: "Gagandeep Singh S/O Gurudip Singh",
    station: "Banda",
    bankAccountNumber: "16222191020327",
    ifscCode: "PUNB0162210",
    panNumber: "FDTPS5882K",
    aadharNumber: "538595363337",
    village: "Umrapur M",
    postOffice: "Azmatpur",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242042",
  },
  {
    name: "Gurdev Singh S/O Jeet Singh",
    station: "Banda",
    bankAccountNumber: "50200102739542",
    ifscCode: "HDFC0004846",
    panNumber: "BCYPS2871J",
    aadharNumber: "905605102389",
    village: "Kundra",
    postOffice: "D Ghanshyam",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242042",
  },
  {
    name: "Inderjeet Singh S/O Fakir Singh",
    station: "Banda",
    bankAccountNumber: "321351000330",
    ifscCode: "ICIC0003213",
    panNumber: "FYLPS1570R",
    aadharNumber: "514934392502",
    village: "Koora",
    postOffice: "Azmatpur",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242042",
  },
  {
    name: "Jaspal Singh S/O Baldev Singh",
    station: "Banda",
    bankAccountNumber: "50100792037930",
    ifscCode: "HDFC0004846",
    panNumber: "BUJPJ4458F",
    aadharNumber: "948407274666",
    village: "Padriya Dalelpur",
    postOffice: "Banda (Shahjahanpur)",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242042",
  },
  {
    name: "Kalvinder Singh S/O Gurmel Singh",
    station: "Banda",
    bankAccountNumber: "04941000004049",
    ifscCode: "PSIB0000494",
    panNumber: "GRSPS1697Q",
    aadharNumber: "319998625688",
    village: "Dhimarpur",
    postOffice: "Azmatpur",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242042",
  },
  {
    name: "Kamaldeep Singh S/O Jasveer Singh",
    station: "Banda",
    bankAccountNumber: "34911196586",
    ifscCode: "SBIN0001668",
    panNumber: "FYQPS1178N",
    aadharNumber: "228303683288",
    village: "Miyanpur",
    postOffice: "Powayan",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242401",
  },
  {
    name: "Kamaljeet Singh S/O Shiv Raj Singh",
    station: "Banda",
    bankAccountNumber: "08290100001933",
    ifscCode: "BARB0BANDAX",
    panNumber: "BVXPS5644B",
    aadharNumber: "664716098206",
    village: "Powayan Road",
    postOffice: "Banda (Shahjahanpur)",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242042",
  },
  {
    name: "Kuldeep Singh S/O Laxman Singh",
    station: "Banda",
    bankAccountNumber: "50100415532372",
    ifscCode: "HDFC0004846",
    panNumber: "FECPS5131F",
    aadharNumber: "398020087988",
    village: "Indlapur",
    postOffice: "Mohiuddinpur",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242042",
  },
  {
    name: "Lakhvinder Singh S/O Gurumukh Singh",
    station: "Banda",
    bankAccountNumber: "50100475135565",
    ifscCode: "HDFC0004846",
    panNumber: "GXCPS1661G",
    aadharNumber: "983986695188",
    village: "Ghanshyampur",
    postOffice: "Bilsanda",
    policeStation: "Bisalpur Police Station",
    district: "Pilibhit",
    state: "Uttar Pradesh",
    pincode: "262202",
  },
  {
    name: "Manjeet Singh S/O Harjindar Singh",
    station: "Banda",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: "FDYPS3087K",
    aadharNumber: "906176404118",
    village: "Miyanpur",
    postOffice: "Behtasambad",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242401",
  },
  {
    name: "Paramjeet Singh S/O Malkeet Singh",
    station: "Banda",
    bankAccountNumber: "915030030682263",
    ifscCode: "UTIB0000823",
    panNumber: "FZPPS9633N",
    aadharNumber: "855295744034",
    village: "Kundra",
    postOffice: "Dudwa",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242042",
  },
  {
    name: "Sukhjit Singh S/O Mahanga Singh",
    station: "Banda",
    bankAccountNumber: "04941000014660",
    ifscCode: "PSIB0000494",
    panNumber: "GCUPS3304H",
    aadharNumber: "540506116466",
    village: "Bhauar Khera Khurd",
    postOffice: "Banda (Shahjahanpur)",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242042",
  },
  {
    name: "Vishal Sharma S/O Tirath Ram Sharma",
    station: "Banda",
    bankAccountNumber: "000613000016326",
    ifscCode: "UPCB00SJDCB",
    panNumber: "BEMPV2361C",
    aadharNumber: "926476048130",
    village: "Dadiuri",
    postOffice: "Mohiuddinpur",
    policeStation: "Powayan Police Station",
    district: "Shahjahanpur",
    state: "Uttar Pradesh",
    pincode: "242042",
  },
  {
    name: "Abhi Singh S/O Om Pal Singh",
    station: "Puranpur",
    bankAccountNumber: "59760100003379",
    ifscCode: "BARB0PURPIL",
    panNumber: "PXVPS8248P",
    aadharNumber: "795158310916",
    village: null,
    postOffice: "Abhaipur",
    policeStation: "Puranpur Police Station",
    district: "Pilibhit",
    state: "Uttar Pradesh",
    pincode: "262122",
  },
  {
    name: "Sukhdev Singh S/o Arjun Singh",
    station: "Bazpur",
    bankAccountNumber: "14522191006775",
    ifscCode: "PUNB0145210",
    panNumber: null,
    aadharNumber: "290115904002",
    village: "Bakhtapur",
    postOffice: "Bhagwantapur",
    policeStation: "Puranpur Police Station",
    district: "Pilibhit",
    state: "Uttar Pradesh",
    pincode: "262122",
  },
  {
    name: "Amandeep Singh S/O Kashmir Singh",
    station: "Puranpur",
    bankAccountNumber: "11598742100",
    ifscCode: "SBIN0017186",
    panNumber: "CANPS7825J",
    aadharNumber: "444082597139",
    village: "Lochanpur",
    postOffice: "Mailani",
    policeStation: "Gola Police Station",
    district: "Lakhimpur Kheri",
    state: "Uttar Pradesh",
    pincode: "262803",
  },
  {
    name: "Avtar Singh S/O Arjun Singh",
    station: "Puranpur",
    bankAccountNumber: "922010016862955",
    ifscCode: "UTIB0001848",
    panNumber: "DADPS4663D",
    aadharNumber: "720336733906",
    village: "Gurunanak Farm",
    postOffice: "Rampura Fakire",
    policeStation: "Puranpur Police Station",
    district: "Pilibhit",
    state: "Uttar Pradesh",
    pincode: "262122",
  },
  {
    name: "Goldanjeet Singh S/O Nahar Singh",
    station: "Puranpur",
    bankAccountNumber: "11071600000524",
    ifscCode: "PSIB0021107",
    panNumber: "IKRPS1833L",
    aadharNumber: "855101434538",
    village: "Banjarganj",
    postOffice: "Gulabtanda",
    policeStation: "Puranpur Police Station",
    district: "Pilibhit",
    state: "Uttar Pradesh",
    pincode: "262122",
  },
  {
    name: "Hardeep Singh S/O Mukhtiar Singh",
    station: "Puranpur",
    bankAccountNumber: "3551430025",
    ifscCode: "CBIN0285024",
    panNumber: "HEDPS7478C",
    aadharNumber: "445807304861",
    village: "Gurunanak Farm",
    postOffice: "Rampura Fakire",
    policeStation: "Puranpur Police Station",
    district: "Pilibhit",
    state: "Uttar Pradesh",
    pincode: "262122",
  },
  {
    name: "Pavan Kumar S/O Dharam Singh",
    station: "Puranpur",
    bankAccountNumber: "NO PAYMENT DONE",
    ifscCode: "NO PAYMENT DONE",
    panNumber: "EVEPS8812M",
    aadharNumber: "903162711763",
    village: "Bakhtapur",
    postOffice: "Sabalpur",
    policeStation: "Puranpur Police Station",
    district: "Pilibhit",
    state: "Uttar Pradesh",
    pincode: "262122",
  },
  {
    name: "Jagtar Singh S/O Shri Pal Singh",
    station: "Puranpur",
    bankAccountNumber: "45030100002013",
    ifscCode: "BARB0MOHLAK",
    panNumber: "BPZPS3128A",
    aadharNumber: "442765739661",
    village: "Gram",
    postOffice: "Saraunia",
    policeStation: "Mohammadi Police Station",
    district: "Lakhimpur Kheri",
    state: "Uttar Pradesh",
    pincode: "261505",
  },
  {
    name: "Jaspal Singh S/O Amar Singh",
    station: "Puranpur",
    bankAccountNumber: "NO PAYMENT DONE",
    ifscCode: "NO PAYMENT DONE",
    panNumber: "IFZPS2192B",
    aadharNumber: "989147984948",
    village: "Nauranabad",
    postOffice: "Naujalia Nakatia",
    policeStation: "Puranpur Police Station",
    district: "Pilibhit",
    state: "Uttar Pradesh",
    pincode: "262122",
  },
  {
    name: "Jasvinder Singh S/O Mohan Singh",
    station: "Puranpur",
    bankAccountNumber: "06970100008148",
    ifscCode: "BARB0PURANP",
    panNumber: "FJMPS7230C",
    aadharNumber: "650187418091",
    village: "Muradpur",
    postOffice: "Sabalpur",
    policeStation: "Puranpur Police Station",
    district: "Pilibhit",
    state: "Uttar Pradesh",
    pincode: "262122",
  },
  {
    name: "Ompal S/O Raghuraj Singh",
    station: "Puranpur",
    bankAccountNumber: "06970100023956",
    ifscCode: "BARB0PURANP",
    panNumber: null,
    aadharNumber: "403409453622",
    village: "Sabalpur Khas",
    postOffice: "Sabalpur",
    policeStation: "Puranpur Police Station",
    district: "Pilibhit",
    state: "Uttar Pradesh",
    pincode: "262122",
  },
  {
    name: "Parjeet Kaur D/O Gurdeep Singh",
    station: "Puranpur",
    bankAccountNumber: "684310110015588",
    ifscCode: "BKID0006843",
    panNumber: "BUSPK9254R",
    aadharNumber: "809881441702",
    village: "Pachpeda Prahladpur",
    postOffice: "Udaikaranpur",
    policeStation: "Puranpur Police Station",
    district: "Pilibhit",
    state: "Uttar Pradesh",
    pincode: "262122",
  },
  {
    name: "Saravjeet Singh S/O Baljeet Singh",
    station: "Puranpur",
    bankAccountNumber: "14522191021419",
    ifscCode: "PUNB0145210",
    panNumber: "EIRPS5431J",
    aadharNumber: "385984472143",
    village: "Sundarpur",
    postOffice: "Rudrapur",
    policeStation: "Puranpur Police Station",
    district: "Pilibhit",
    state: "Uttar Pradesh",
    pincode: "262122",
  },
  {
    name: "Paramjeet Singh S/O Naseeb Singh",
    station: "Bilaspur",
    bankAccountNumber: "913010044954406",
    ifscCode: "UTIB0001675",
    panNumber: "BPHPS1703K",
    aadharNumber: "268766431328",
    village: "Sector 90-91 Mohali",
    postOffice: "Chandigarh Sector 55",
    policeStation: null,
    district: "S.A.S. Nagar (Mohali)",
    state: "Punjab",
    pincode: "160055",
  },
  {
    name: "Gagandeep Singh S/O Bhajan Lal",
    station: "Afzalgarh",
    bankAccountNumber: null,
    ifscCode: null,
    panNumber: null,
    aadharNumber: null,
    village: null,
    postOffice: null,
    policeStation: null,
    district: null,
    state: null,
    pincode: null,
  },
];
